#!/usr/bin/env bash

# Get the branch name
branch="$(git branch | grep "\*" | awk '{print $2}')"

if [ ! -d "~/.gitdiffs" ]; then
  mkdir ~/.gitdiffs
fi

# Write the diff between master and this branch to a tmp file
git diff master..$branch > ~/.gitdiffs/$branch.diff

gist -p -d "$branch Diff" ~/.gitdiffs/$branch.diff

