#!/usr/bin/env bash

# Get the branch name
branch="$(git branch | grep "\*" | awk '{print $2}')"

if [[ ! -d "${HOME}/.gitdiffs" ]]; then
  mkdir ${HOME}/.gitdiffs
fi

# Write the diff between master and this branch to a tmp file
filename="${HOME}/.gitdiffs/$branch.$(date +'%Y%m%d.%H%M%S').diff"
git diff master > $filename
jist -d "$branch Diff" -o  $filename

